name: ACA Bot CI/CD

on:
  push:
    branches: [ v0.1-launch, main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r bot/requirements.txt
          pip install pytest pytest-asyncio
      
      - name: Run security audit
        run: |
          pip install safety
          safety check --json
      
      - name: Run tests
        run: pytest bot/tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker build -t aca-bot:${{ github.sha }} -f infra/Dockerfile .
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/aca-bot
            docker pull aca-bot:${{ github.sha }}
            docker-compose up -d